<#
https://projecteuler.net/problem=12

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
#>

$NthTriangleNumber = 3
$TriangleNumber = 6

$MaxDivisors = 0
$MaxNth = 0

$Divisors = 0

While($MaxDivisors -lt 501){

    If(($TriangleNumber % 4) -eq 0){
    If(($TriangleNumber % 3) -eq 0){
    If(($TriangleNumber % 5) -eq 0){

    ForEach($TestDivisor in 1..($TriangleNumber/2)){
        If(($TriangleNumber % $TestDivisor) -eq 0){
            $Divisors++
            }
        }
    
    Write-Host "Triangle number" $TriangleNumber "-" $Divisors "divisors, Nth triangle:" $NthTriangleNumber "max:" $MaxDivisors
    
    If($Divisors -gt $MaxDivisors){
        $MaxDivisors = $Divisors
        $MaxNth = $NthTriangleNumber  
        }

    }}}

    $NthTriangleNumber++
    $TriangleNumber = $TriangleNumber + $NthTriangleNumber
    $Divisors = 0
   
    }


    








