<#
https://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#>

$Array = @(1, 2)

while($Array[-1] -lt 4000000){

$Array += ($Array[-1] + $Array[-2]) # add the last number to the second last, and append the result
}


$Total = 0

foreach($Entry in $Array){

if($Entry % 2 -eq 0){ $Total = $total + $Entry}
}

Write-Output "`nBy considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms:"
$Total.ToString('N0')
